### ISSUE TITLE
[Windows|MinGW] Unable to pass assert at assets_storage on line 37

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#1]
Hello.

I see [your article](https://habrahabr.ru/post/303142/) and try to make [desktop application](https://github.com/TheVice/elements/tree/vicemaster): on Windows by compiling in MinGW.
Unfortunately I can not run app success, app do not pass [assert checking](https://github.com/PkXwmpgN/elements/blob/master/elements/assets/assets_storage.cpp#L37) of instance of storage
if I uncomment [line 28](https://github.com/TheVice/elements/blob/vicemaster/platform/desktop/RenderDemo.cpp#L28) that command to initialize rendered class.

Can you give an advice how to deal with this situation?

Thanks.

P.S.
I try only on air sample, so I change paths to [windows order](https://github.com/TheVice/elements/blob/vicemaster/experiments/air/pass_particles.cpp#L51) only for this experiment sample.
But it seems that assert checking before try to read by the file paths.

**Comment by PkXwmpgN** [comment]
Hello.

You must [initialize](https://github.com/TheVice/elements/blob/master/elements/assets/assets_storage.h#L40) the singleton with an object that describes the platform details.
It is a derived class from [asset_reader](https://github.com/TheVice/elements/blob/master/elements/assets/assets_storage.h#L34) abstraction.
Something like this:
```c++
struct my_asset_reader : public eps::asset_reader
{
    // root path to asset folder. For example, C:\elements\assets
    explicit my_asset_reader(std::string & root);

    bool visit(eps::asset_texture & asset) final
    {
        // path to asset, for example "shaders/experiments/air/particles.prog"
        const std::string & asset_path = asset.resource();
        // normalize and concatenate asset_path with root.
        // result is platform specific ('/' or '\\')
        // for example, see std::filesystem to hide this details
        const std::string result = ...;

        // create the file abstraction.
        // derived class from asset_read_operation (elements/assets/asset_operations.h)
        // for example, elements/assets/asset_operations_stream.h

        eps::asset_read_operation_stream opt(result.c_str());

        // load
        if(asset.load(&opt))
            return true;
    }

    bool visit(eps::asset_blob & asset) final;
    bool visit(eps::asset_xml & asset) final;

private:
    std::string root_;
};
```

Initialization:
```C++
eps::assets_storage::init<my_asset_reader>("C:\\elements\\assets");
```

By the way, Windows can't support OpenGL ES directly. You must use Qt or emulator like [this](http://malideveloper.arm.com/resources/tools/opengl-es-emulator/) or rewrite shaders.

Thank you for enquiring.

**Comment by TheVice** [comment]
Thanks.

Something like [this](https://github.com/TheVice/elements/blob/vicemaster/platform/desktop/desktop_asset_reader.h).

About OpenGL ES on Windows: I use [glew](https://github.com/nigels-com/glew) that it seems deal with this API on this platform. Otherwise how I located [here](https://github.com/PkXwmpgN/elements/blob/master/elements/rendering/utils/program_loader.cpp#L93).

Alight, now initialization pass. But some other assert checking do not pass when construct method called.
But this situation for [other issue](https://github.com/PkXwmpgN/elements/issues/2). This is resolved so I close it.

Thanks again.

**Comment by TheVice** [comment]
> By the way, Windows can't support OpenGL ES directly. You must use Qt or emulator like [this](http://malideveloper.arm.com/resources/tools/opengl-es-emulator/) or rewrite shaders.

Also on days present addition solution - [SwiftShader](https://swiftshader.googlesource.com/SwiftShader), article on [OpenNET](http://www.opennet.ru/opennews/art.shtml?num=44697).

Not all samples can be [run](https://github.com/TheVice/elements/tree/SwiftShader) with this library, ```fire``` and ```liquid``` fails with next run-time output:
```
SwiftShader/src/OpenGL/compiler/OutputASM.cpp:2986:
int glsl::OutputASM::samplerRegister(TIntermTyped*): Assertion `false' failed.
```

But at least ```light``` demo can be run proper with libraries from that project
![light](https://cloud.githubusercontent.com/assets/5098854/16507217/d125c118-3f30-11e6-9a88-b526167492a3.jpg)
Even with good FPS value - 64.10 on screen-shoot.

**Comment by PkXwmpgN** [comment]
Hello.

Google also added this solution to Android Emulator. This is very slow.

> light demo can be run proper with libraries from that project
> Even with good FPS value - 64.10 on screen-shoot

I think it is not proper. At first, wrap of the background texture is not correct. Secondary, no the light-scattered effect. 

Thank you.

**Comment by TheVice** [comment]
Hello.

I [synchronize](https://github.com/TheVice/elements/commit/53af3133842884e96c53f92b4e67620260e93a03) the variable values for desktop demo application,
files platform/android/elements/<demo name>/src/main/res/xml/preferences.xml used as data sourece
Last version of light view like this:  
![light](https://cloud.githubusercontent.com/assets/5098854/16558401/23094878-41ee-11e6-86fa-36686624b274.jpg)

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

Looks great! 
Thank you.
