### ISSUE TITLE
[Windows|MinGW] Unable to pass assert at future on line 130

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#2]
Hello.

Air sample still can not run proper if I uncomment [line 34](https://github.com/TheVice/elements/blob/vicemaster/platform/desktop/RenderDemo.cpp#L34) that command to construct rendered class.
[This assert checking](https://github.com/PkXwmpgN/elements/blob/master/elements/synchronization/future.h#L130) do not pass.

Can you help again to handle this situation?

Thanks.

**Comment by PkXwmpgN** [comment]
Hello.

The Air renderer deals with velocities field, that is generated [Air subsystem].(https://github.com/TheVice/elements/blob/master/elements/simulation/air/system.h#L35)
So, you must create the simulation and transfer an output to renderer. 

```c++
// create simulation subsystem somewhere
eps::simulation::air::system simulation;
// construct with window size
simulation.construct(size);
// spawn simulation
renderer.set_field(simulation.spawn(1.0f / 60.0f));
// construct renderer
renderer.construct(size, particles_count);

```

A simulation subsystem also needed for Liquid and Light Scattered

Thank you.

**Comment by TheVice** [comment]
Yes, that code resolve this issue.

Thanks.
