### ISSUE TITLE
[Flame Simulation] setup the demo

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#3]
Hello.

With your help two demos (AirDemo, StrangeDemo) already see like on your screenshoots.
However FlameSimulation have some strange view
![flame simulation](https://cloud.githubusercontent.com/assets/5098854/16093703/afbfdba4-3345-11e6-94c8-17b9506ce632.jpg)

Can you give me an advice how to setup this demo?

For now used [next setup](https://github.com/TheVice/elements/blob/f875169/platform/desktop/fire/FireDemo.cpp#L24):
	  mParticlesCount(10)
//...
	mRenderer = std::make_unique<eps::experiment::fire::renderer>();

	if (!mRenderer->initialize())
	{
		throw std::runtime_error("mRenderer->initialize() failed");
	}

	mRenderer->set_background("textures/noise.png");
	//
	mRenderer->set_intensity(5.0f);
	//
	mRenderer->set_covering(5.0f);
	//
	mRenderer->set_color_hot(glm::vec3(1.0f, 0.0f, 0.0f));
	//
	mRenderer->set_color_cold(glm::vec3(0.0f, 1.0f, 1.0f));
	// construct renderer
	mRenderer->construct(size, mParticlesCount);

Thanks.

**Comment by PkXwmpgN** [comment]
Hello.

The second parameter of [construct](https://github.com/PkXwmpgN/elements/blob/master/experiments/fire/renderer.h#L42) method is not the quantity of particles. It is a size of the internal texture. The big texture the better quality and the worse performance.

```c++
mRenderer->construct(size, 512);
```
The intensity and the covering must be a normalized value [0.0, 1.0]. Default values are 0.5 and 1.0. They can be changed after construction.

Thank you

**Comment by TheVice** [comment]
Thank you, that I looking for.
