### ISSUE TITLE
 [Liquid Simulation] setup the demo

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#5]
Hello.

Liquid Simulation is one of the demos which has the largest number of configurable options that several confusing at first.

Can you help to understand what value will be OK for that parameters?
Current [setup next](https://github.com/TheVice/elements/blob/4e1856c/platform/desktop/liquid/LiquidDemo.cpp#L26)

	// create simulation subsystem
	mSystem = std::make_unique<eps::simulation::liquid::system>();
	// construct with window size
	mSystem->construct(size, mParticlesCount);
	//
	mSystem->set_gravity(glm::vec2(1.0f, 1.0f));
	//
	mSystem->set_density(100.0f);
	//
	mSystem->set_viscosity(10.0f, 10.0f);
	//
	mSystem->set_pressure(10.0f, 10.0f);
	//
	mSystem->set_elasticity(10.0f);
	//
	mRenderer = std::make_unique<eps::experiment::liquid::renderer>();

	if (!mRenderer->initialize())
	{
		throw std::runtime_error("mRenderer->initialize() failed");
	}

	// spawn simulation
	mRenderer->set_particles(mSystem->spawn(1.0f / 60.0f));
	//
	const std::string pathToTexture = "textures/noise.png";
	mRenderer->set_surface_background(pathToTexture);
	//
	mRenderer->set_surface_color(glm::vec4(1.0f, 0.5f, 0.25f, 1.0f));
	// construct renderer
	const glm::uvec2 sim_size(size.x, size.y);
	mRenderer->construct(size, sim_size, 512);

Also touch monitoring

	glm::dvec2 pos;
	glfwGetCursorPos(mGame->GetWindow(), &pos.x, &pos.y);
	pos.y = mGame->GetScreenHeight() - pos.y;

	if (glfwGetMouseButton(mGame->GetWindow(), GLFW_MOUSE_BUTTON_LEFT))
	{
		GLfloat radius = 5.0f;
		mSystem->touch(glm::vec2(pos.x, pos.y), radius);
	}

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

Values of configurable options depend on the size of simulation. You can see construction from [Android](https://github.com/PkXwmpgN/elements/blob/master/platform/android/elements/libs/Elements/src/main/jni/liquid/liquid_renderer.cpp#L66) and use the same.

```c++
float ratio = (float)window_size.y / (float)window_size.x;
simulation_size = vec2(10.0f, 10.0f * ratio);
```
Options [here](https://github.com/PkXwmpgN/elements/blob/master/platform/android/elements/libs/Elements/src/main/jni/liquid/liquid_config.cpp#L40)

```c++
// -----------------------
// density
const float LIQUID_DENSITY_DEFAULT = 30.0f;
const float LIQUID_DENSITY_MIN = 0.0f;
const float LIQUID_DENSITY_MAX = 50.0f;

// -----------------------
// viscosity
const float LIQUID_VISCOSITY_SIGMA_DEFAULT = 1.0f;
const float LIQUID_VISCOSITY_SIGMA_MIN = 0.0f;
const float LIQUID_VISCOSITY_SIGMA_MAX  = 10.0f;
const float LIQUID_VISCOSITY_BETA_DEFAULT  = 0.1f;
const float LIQUID_VISCOSITY_BETA_MIN = 0.0f;
const float LIQUID_VISCOSITY_BETA_MAX = 1.0f;

// -----------------------
// pressure
const float LIQUID_PRESSURE_DEFAULT  = 0.3f;
const float LIQUID_PRESSURE_MIN  = 0.1f;
const float LIQUID_PRESSURE_MAX  = 1.1f;
const float LIQUID_PRESSURE_NEAR_DEFAULT = 6.0f;
const float LIQUID_PRESSURE_NEAR_MIN = 1.0f;
const float LIQUID_PRESSURE_NEAR_MAX = 21.0f;

// elasticity
const float LIQUID_ELASTICITY_DEFAULT = 10.0f;
const float LIQUID_ELASTICITY_MIN  = 0.0f;
const float LIQUID_ELASTICITY_MAX = 100.0f;
```

And then you must convert your touch(screen) coordinates to simulation coordinates.
On Android it look like [this](https://github.com/PkXwmpgN/elements/blob/master/platform/android/elements/libs/Elements/src/main/jni/liquid/liquid_renderer.cpp#L99).

```c++
// setup transformation matrix
transform = eps::math::translate(0.0f, sim_size.y, 0.0f) *
    eps::math::scale(sim_size.x, -sim_size.y, 1.0f) *
    eps::math::scale(1.0f / size.x, 1.0f / size.y, 1.0f);

// touch
const eps::math::vec4 pos = transform * eps::math::vec4(screen_x, screen_y, 1.0f, 1.0f);
if(action == AMOTION_EVENT_ACTION_MOVE)
    simulation->touch(eps::math::vec2(pos.x, pos.y), 1.0f);
else
   simulation->touch(eps::math::vec2(pos.x, pos.y), 0.0f);
```

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

Did it help you? Can we close the issue?

Thank you.

**Comment by TheVice** [comment]
Hello.

From your side you do all possible to make desktop port much similar to Android build: consult in this issue theme, added source of Android build. From my side, on [current stage](https://github.com/TheVice/elements/tree/1a98c53/platform/desktop), Liquid Simulation has no reaction to mouse pointer even if I do not check if left mouse key pushed down. Demo display only ```textures/noise.png```

So it is only desktop port issue and for now current issue will be closed.
From my side I view two way to port to desktop this demo: by debugger view states of key classes for Android build and make setting of this class on desktop port, or just simply embed your classes from [jni folder](https://github.com/PkXwmpgN/elements/tree/master/platform/android/elements/libs/Elements/src/main/jni/liquid) with disabled by macros ANDROID specific things.
I actually that try with liquid_config class with disabled ```#include "logging.h"``` and dot no using preferences class.

I will inform, comment to closed issue are allowed, if find that things that prevent to fully re-implement the desktop port.

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

Perhaps, the issue is [here](https://github.com/TheVice/elements/blob/vicemaster/platform/desktop/liquid/LiquidDemo.cpp#L36)

```c++
mSystem->construct(size, mParticlesCount);
```

Try to use [sim_size](https://github.com/TheVice/elements/blob/vicemaster/platform/desktop/liquid/LiquidDemo.cpp#L63) to construct.
```c++
const glm::uvec2 sim_size(10.0f, 10.0f * mGame->GetAspectRatio());
mSystem->construct(sim_size, mParticlesCount);

```

Thank you.

**Comment by TheVice** [comment]
Hello.

Unfortunately this is do not help to view something than background image.

Meanwhile I [embedding the Android](https://github.com/TheVice/elements/tree/e85b72a/platform/desktop) demo into desktop: I added preferences class that get only default values and nothing to set;
on Demo side there is two variants (B and C) - with using directly liquid_renderer class (B) and with liquid_renderer_factory.
[Touch method](https://github.com/TheVice/elements/blob/e85b72a2e74238cba945889d1978e4e75676b2c2/platform/android/elements/libs/Elements/src/main/jni/liquid/liquid_renderer.cpp#L190) now call twice: with radius 1.0f and with 0.0f, but even if I commented one of this call nothing happen.

Thank you.

**Comment by TheVice** [comment]
Well, after [adapting shader](https://github.com/TheVice/elements/commit/0d92c6603dccf480bb37fbda6a54ed5e92a39d56#diff-38c1bb06ba9fa0d93d655f713f664889) for work with SwiftShader demo show like it must
![screenshot from 2016-07-01 18-27-56](https://cloud.githubusercontent.com/assets/5098854/16526511/43d83fa4-3fba-11e6-983b-1dda653f8f6e.png)

So for desktop port demo finally was setup.

**Comment by TheVice** [comment]
Hello.

Also as in [case](https://github.com/PkXwmpgN/elements/issues/1#issuecomment-230263440) with ```light``` demo ```liquid``` demo too view the same like on Android
![liquid](https://cloud.githubusercontent.com/assets/5098854/16700935/7b96737e-4565-11e6-853f-64b0fb9494b0.jpg)
But only if SwiftShader used - so means, as use say before, not at full performance - GPU acceleration not used in this case.

Meanwhile I [checking](https://github.com/TheVice/elements/tree/ShaderVisualization) what actually shaders do on desktop platform with out SwiftShader. And as result I detect that [shaders/experiments/liquid/particles.prog](https://github.com/PkXwmpgN/elements/blob/94ff018/assets/shaders/experiments/liquid/particles.prog) shader do not [display](https://github.com/TheVice/elements/tree/ShaderVisualization/platform/desktop/experiments/liquid/particles) anything until 'if condition' changed or disabled fully at fragment shader.
So I commenting ( minus of 1.0 will be do same result )
~~vec2 pos = gl_PointCoord * 2.0 - 1.0;~~
~~if(dot(pos, pos) > 1.0)~~
~~discard;~~
and leave only
```
gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
```
and see next on desktop platform
![liquid_desktop](https://cloud.githubusercontent.com/assets/5098854/16701249/37d651a2-4567-11e6-873f-37780e4c9ca1.jpg)
In dynamic (gif animation) it looks like [this](http://giphy.com/gifs/3o6Zt7qFUyNgKHLbk4)

I just share with some results of research on theme - why only background visible and no particles on the screen.

Thank you.

**Comment by PkXwmpgN** [comment]
Hello!

That is interesting. 
I believe it happens because gl_PointCoord is always zero. On desktop OpenGL version the "GL_POINT_SPRITE" state is disable by default.

Try to call during initialization
```
glEnable(GL_POINT_SPRITE); // for example, Qt needs that
// optionaly
// glEnable(GL_VERTEX_PROGRAM_POINT_SIZE)
```

Thank you.

**Comment by TheVice** [comment]
Hello!

Yes, you absolutely right. Setting both states to enable will resolve issue with drawing particles in ```light``` and ```liquid``` demos on desktop with out SwiftShader library.

Thank you.
