### ISSUE TITLE
[Windows|Clang] possible memory leaks at future.h on line 58

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#6]
Hello.

After exit from desktop versions of Air, Light and Liquid there are messages that memory leak present. As explanation debugger say that potential problem at [future.h on line 58](https://github.com/PkXwmpgN/elements/blob/f3f7022/elements/synchronization/future.h#L58).

Can you confirm or disprove messages of runtime checking?

Fire and Strange have no message about memory leaks.

Thank you.

P.S.
Fire, Light and Liquid have embedded android demos, in other words they have render factory class object.
Air and Strange construct the system (only Air demo) and render class objects by self.

**Comment by PkXwmpgN** [comment]
Hello.

Fire and Strange don't use the simulation subsystems. The simulation subsystem make a calculation in a separate thread and use future object to transport the calculation result to a renderer. 

We have two references in the internal state of the transport mecha after the simulation has been running. The first reference is owned the [promise](https://github.com/PkXwmpgN/elements/blob/master/elements/synchronization/future.h#L90) object, it is owned the separate [thread](https://github.com/PkXwmpgN/elements/blob/master/elements/simulation/liquid/system.cpp#L73). The second references is owned the [future](https://github.com/PkXwmpgN/elements/blob/master/elements/synchronization/future.h#L136) object, it is owned the [renderer](https://github.com/PkXwmpgN/elements/blob/master/experiments/liquid/pass_particles.cpp#L42). 

if the result is no longer needed, the future object will be destroyed (renderer will be destroyed) and the reference counter will be one. if the reference count is one, the appropriate [promise](https://github.com/PkXwmpgN/elements/blob/master/elements/simulation/liquid/system.cpp#L76) object will be [invalid](https://github.com/PkXwmpgN/elements/blob/master/elements/synchronization/future.h#L74). Then the thread will be stopped. Consequently, we have lost the last reference to the internal state. 

On Android we [destroy](https://github.com/PkXwmpgN/elements/blob/master/platform/android/elements/libs/Elements/src/main/jni/liquid/liquid_jni.cpp#L137) the renderer, but the application will not be stopped. We have a time to stop the simulation thread automatically and clean appropriate resources.

I think it is fine.

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

Let the task stay at open status. I will push additional synchronization soon.

Thank you.

**Comment by TheVice** [comment]
Hello.

Great.

Meanwhile on desktop side I choose next temporary solution:
on Air and at A variant on Liquid simply pause between render and system release

	mRenderer.reset(nullptr);
	//
	using namespace std::literals;
	std::this_thread::sleep_for(5s);
	//
	mSystem.reset(nullptr);

For demos that use render factory or named render object, both types encapsulate creation of system and render, addition pause required before close/release.
Otherwise vector assert with out of range may happen here - [volume line 203](https://github.com/PkXwmpgN/elements/blob/f3f7022494f3750e674480dfa6ddeb3fd2fa29b4/elements/simulation/air/volume.cpp#L203) if particles still make circle. 

This not ideal, success depend on system performance, special CPU, but even this variant solve this issue for Air demo and A variant of Liquid. All demos with encapsulate creation of system and render may still output message about memory leaks.

Thank you.

**Comment by PkXwmpgN** [comment]
Hello.

I pushed the [commit](https://github.com/PkXwmpgN/elements/commit/086ddb4a32e6114cb6914987cecd8ec7fc71eae0) with task-based synchronization improvements. 
This have to resolve the issue. 

Could you please confirm?

Thank you.

**Comment by TheVice** [comment]
Hello.

Thank for your work. I [merge](https://github.com/TheVice/elements/commit/d18983d845339903eb301f66470bad23cfa2c415) your changes, so no pauses from desktop side are need any more.
So I close this issue as resolved.

Thanks again.
