### ISSUE TITLE
[assimp-3.2] memory leak for some models

### ISSUE THREAD

**Issue by TheVice** [PkXwmpgN/elements#8]
Hello.

I do not know what 3d models you [planed](https://github.com/PkXwmpgN/elements/commit/121884b31891bc54e3b7d0fcc1d2944b7cd55b4c) to use with this library, but for some models there is a memory leak in assimp [version 3.2](https://github.com/assimp/assimp/releases/tag/v3.2) that created at [code/ObjFileImporter.cpp on line 297](https://github.com/assimp/assimp/blob/c318d648ff73aa2e32b783709d69740ac3e8c072/code/ObjFileImporter.cpp#L297).
To prevent this situation [version 3.3](https://github.com/assimp/assimp/releases/tag/v3.3) available or, if use of 3.2 is preferred, commit [3c9e57fd73db479d66fc654fe4a7171dd6432fd8](https://github.com/assimp/assimp/commit/3c9e57fd73db479d66fc654fe4a7171dd6432fd8) fixed this memory leak.

Have a nice day.

**Comment by PkXwmpgN** [comment]
Hello.

Assimp updated to v3.3.1

Thank you.
